# Numpy

In [30]:
import numpy as np

# Arrays NumPy Unidimensional

In [31]:
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)
print(my_array.shape)

[1 2 3 4 5]
(5,)


# Arrays NumPy Multidimensionais

In [32]:
my_array = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(my_array[0])
print(my_array[1])
print(my_array.shape)
my_array[0] = -1
print(my_array)

[1 2 3 4 5]
[1 2 3 4 5]
(2, 5)
[[-1 -1 -1 -1 -1]
 [ 1  2  3  4  5]]


In [33]:
a = np.arange(6).reshape((3, 2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [34]:
my_array = np.array([[4, 5], [6, 1]])
print(my_array[0][1])

5


In [35]:
my_array = np.array([[4, 5], [6, 1]])
print(my_array)

[[4 5]
 [6 1]]


# Iniciando um array com valores aleatórios

In [61]:
x = np.empty([3,2], dtype = int)
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [52]:
my_random_array = np.random.random((5))
print(my_random_array)

[0.17837139 0.54469651 0.13894504 0.25898937 0.44254863]


In [65]:
a = np.floor(10*np.random.random((3,4)))
print(a)

[[0. 5. 8. 1.]
 [4. 2. 6. 3.]
 [5. 7. 1. 7.]]


# Iniciando um array de 0 e de 1

In [66]:
my_new_array = np.zeros((5))
print(my_new_array)

[0. 0. 0. 0. 0.]


In [67]:
my_new_array = np.ones((5))
print(my_new_array)

[1. 1. 1. 1. 1.]


# Indexação e slicing

In [68]:
my_array2 = np.array([3, 2, 8, 22, 127])
my_array2[3]

22

In [69]:
my_array2 = np.array([3, 2, 8, 22, 127])
print(my_array2[1:])

[  2   8  22 127]


In [70]:
my_array2 = np.array([3, 2, 8, 22, 127])
print(my_array2[2:4])

[ 8 22]


# Manipulando array em NumPy

In [73]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])
soma = a + b # Soma
subtracao = a - b # Subtração
multiplicacao = a * b # Multiplicação
divisao = a / b # Divisão
print('Soma = \n', + soma)
print('\n')
print('Subtração = \n', + subtracao)
print('\n')
print('Multiplicação = \n', + multiplicacao)
print('\n')
print('Divisão = \n', + divisao)

Soma = 
 [[ 6.  8.]
 [10. 12.]]


Subtração = 
 [[-4. -4.]
 [-4. -4.]]


Multiplicação = 
 [[ 5. 12.]
 [21. 32.]]


Divisão = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


# Multiplicação de arrays

In [74]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
b = np.array([[5.0, 6.0], [7.0, 8.0]])
matrix_product = a.dot(b)
print('Matrix Product = \n', + matrix_product)

Matrix Product = 
 [[19. 22.]
 [43. 50.]]


# EXERCÍCIO 1
Remova todos os números ímpares de um NumPy Array que vai de 0 a 20

# EXERCÍCIO 2
Dado um NumPy Array unidimensional que vai de 0 a 8, converta-o em um NumPy Array bidimensional e quadrado.

# EXERCÍCIO 3
Dado 2 NumPy Array, sendo o primeiro de tamanho 2 linhas por 5 colunas, com valores de 0 a 9 e outro
de tamanho 3 linhas por 5 colunas, com valores de 10 a 24, crie um terceiro NumPy Array de tamanho 5
linhas por 5 colunas que concatene verticalmente os NumPy Arrays 1 e 2.
Dica: Pesquise as funções hstack e vstack.

# EXERCÍCIO 4
Dados 2 NumPy Arrays:
Array1: [ 0, 10, 20, 40, 60]
Array2: [10, 30, 40]
Faça uma função que retorne os valores iguais entre os 2 arrays.
Dica: Use a função intersect1d.

# EXERCÍCIO 5
Dada a matriz:
array = np.array([[1,2,3,4],
[1,2,3,4],
[5,6,7,8],
[1,2,3,4],
[3,3,3,3],
[5,6,7,8]])
Faça uma função que remova as linhas duplicadas, deixando apenas uma incidência da mesma.
Dica: Use a função unique.